services:
  db:
    image: postgis/postgis
    container_name: access_leg_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"  # Port personnalisé pour PostgreSQL

  geoserver:
    image: kartoza/geoserver
    container_name: geoserver
    environment:
      - GEOSERVER_DATA_DIR=/opt/geoserver/data_dir
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}      
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
    ports:
      - "8085:8080"  # Port personnalisé pour GeoServer
    depends_on:
      - db

  flask:
    build: ./flask_app
    container_name: flask_app
    environment:
      - DATABASE_URL=${FLASK_DATABASE_URL}
    ports:
      - "5001:5000"  # Port personnalisé pour Flask
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:80"  # Port personnalisé pour Nginx
    depends_on:
      - geoserver
      - flask

volumes:
  pgdata:
  geoserver_data: